package cz.cvut.fit.prl.scala.implicits.tools.graphDbEntities;

import org.neo4j.graphdb.RelationshipType;

public enum Relationships implements RelationshipType {
    LOCATED_IN,
    DECLARES,
    DECLARED_BY,
    HAS_VERSION,
    HAS_MODULE,
    HAS_CALLSITE,
    GROUP_ARTIFACT,
    ARTIFACT_DECLARATION,
    HAS_PATH,
    HAS_ACCESS,
    DECLARATION_TYPE,
    DECLARATION_SIGNATURE,
    SIGNATURE_TYPE,
    TYPE,
    TYPEREF_DECLARATION,
    TYPE_PARAMETER,
    UPPER_BOUND,
    LOWER_BOUND,
    PARENT,
    RETURN_TYPE,
    HAS_PARAMETERLIST,
    HAS_PARAMETER,
    IN_LANGUAGE,
    TYPE_ARGUMENT,
    ANNOTATION,
    HAS_IMPLICIT_ARGUMENT_VALUEREF,
    HAS_IMPLICIT_ARGUMENT_CALLSITEREF,
    CONVERSION_FROM,
    CONVERSION_TO
}
