---
title: "Random github projects"
author: "Filip Krikava"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    code_folding: hide
params:
  base_dir: ../../../corpora/4-github
  lib_dir: ../inc
  base_url: http://prl1.ele.fit.cvut.cz:8149
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(fs)
library(tidyverse)
library(feather)
library(DT)

theme_set(theme_minimal())

options(corpus_dir=params$base_dir)

source(path(params$lib_dir, "paths.R"))
source(path(params$lib_dir, "functions.R"))

MIN_SLOC <- 1000
MAX_SLOC <- 15000
N <- 10
```

## Overview

## Load data

```{r}
corpus1 <- read_feather(CORPUS_STAGE1_F)
corpus3 <- read_feather(CORPUS_STAGE3_F)
```

## Selected Projects

```{r}
p_good <- filter(corpus3, implicits_exit_code==0, scala_code >= MIN_SLOC, scala_code <= MAX_SLOC)
p_not_compiled <- filter(corpus3, implicits_exit_code!=0, scala_code >= MIN_SLOC, scala_code <= MAX_SLOC)
p_non_sbt <- filter(corpus1, build_system != "sbt", scala_code >= MIN_SLOC, scala_code <= MAX_SLOC)
p_non_compatibe_sbt <- filter(corpus1, build_system == "sbt", !is_compatible_sbt_version(sbt_version), scala_code >= MIN_SLOC, scala_code <= MAX_SLOC)
p_duplicates <- filter(corpus1, build_system == "sbt", is_compatible_sbt_version(sbt_version), dejavu_duplication > .75, gh_stars < 5, scala_code >= MIN_SLOC, scala_code <= MAX_SLOC)
#p_fake_spark <- filter(corpus1, build_system == "sbt", is_compatible_sbt_version(sbt_version), str_detect(tolower(project_id), "spark"), scala_code > 1e5, project_id != "apache--spark")
```

The duplication is just a try :-)

```{r}
random_project <- function(ps, n) {
  idx <- sample(1:nrow(ps), n, replace=T)
  ps$project_id[idx]
}
```

```{r}
selected <- sapply(
  list(p_good, p_not_compiled, p_non_sbt, p_non_compatibe_sbt, p_duplicates), 
  random_project, 
  n=N
)
```

```{r}
corpus1 %>%
  filter(project_id %in% selected) %>%
  my_datatable(page_size = length(selected))
```


```{r}
write_lines(selected, path(params$base_dir, "../3-sample-set/all-projects.txt"))
```

