---
title: "Pipeline"
output:
 html_document:
    toc: true
    theme: united
editor_options: 
  chunk_output_type: console
params:
  base_dir: "/home/rstudio/work/Research/Projects/scala-corpus/corpora/4-top100"
  file_view_prefix: "/files/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(fs)
library(tidyverse)
library(DT)
library(glue)

PROJECTS_DIR <- "projects"
ANALYSIS_DIR <- "_analysis_"

PROJECTS_FILE <- "projects.txt"

METADATA_STATUS <- "metadata-status.csv"
METADATA_LOG <- "metadata.log"

COMPILE_STATUS <- "compile-status.csv"
COMPILE_LOG <- "compile.log"

SEMANTICDB_STATUS <- "semanticdb-status.csv"
SEMANTICDB_STATS <- "semanticdb-stats.csv"
SEMANTICDB_LOG <- "semanticdb.log"

IMPLICITS_STATUS <- "implicits-status.csv"
IMPLICITS_STATS <- "implicits-stats.csv"
IMPLICITS_EXCEPTIONS <- "implicits-exceptions.csv"
IMPLICITS_LOG <- "implicits.log"
```

```{r aux}
merge_project_csvs <- function(project_ids, files, col_types) {
  stopifnot(length(project_ids) == length(files))
  
  existing_files <- file_exists(files)

  df <- map2_dfr(
    project_ids[existing_files], 
    files[existing_files], 
    ~mutate(read_csv(.y, col_types=col_types), project_id=.x)
  )
  
  if (nrow(df) == 0) {
    data_frame(project_id=character())
  } else {
    select(df, project_id, everything())
  }
}

projects_file <- function(projects, filename) path(params$base_dir, PROJECTS_DIR, projects, ANALYSIS_DIR, filename)

show_dataframe <- function(table) {
  datatable(
    table,
    class='cell-border stripe',
    options=list(pageLength=100),
    escape=FALSE
  )
}

show_task_exit_code_summary <- function(status) {
  count(status, exit_code) %>% 
    knitr::kable()
}

create_link <- Vectorize(function(href, text) {
  glue("<a href='{href}' target='_blank'>{text}</a>")
})

add_project_html_links <- function(df) {
  mutate(
    df, 
    project_id=create_link(origin, project_id), 
    project_path=create_link(
      str_c(params$file_view_prefix, project_path),
      basename(project_path)
    )
  )
}

add_log_html_links <- function(df) {
  mutate_at(df, vars(ends_with("log_file")), function(x) create_link(str_c(params$file_view_prefix, x), basename(x)))
}

add_html_links <- function(df) {
  df %>%
  add_project_html_links() %>%
  add_log_html_links()
}

show_task_all_project_status <- function(df) {
  add_html_links(df) %>%
  select(
    -origin
  ) %>% 
    show_dataframe()
}
```


```{r}
project_ids <- read_lines(path(params$base_dir, PROJECTS_FILE))
projects <- data_frame(
    project_id=project_ids,
    origin=str_c("https://github.com/", str_replace(project_id, "--", "/")),
    project_path=path(params$base_dir, PROJECTS_DIR, project_id)
)
```

```{r}
metadata_status <- read_csv(path(params$base_dir, METADATA_STATUS), col_types="cii")
compile_status <- read_csv(path(params$base_dir, COMPILE_STATUS), col_types="cii")
semanticdb_status <- read_csv(path(params$base_dir, SEMANTICDB_STATUS), col_types="cii")
implicits_status <- read_csv(path(params$base_dir, IMPLICITS_STATUS), col_types="cii")
implicits_stats <- read_csv(path(params$base_dir, IMPLICITS_STATS), col_types="cciii")
```

```{r}
projects <- local({
  w_metadata <- left_join(
    projects,
    select(metadata_status, project_id, metadata_status=exit_code, metadata_duration=duration),
    by="project_id"
  )
  w_compile <- left_join(
    w_metadata,
    select(compile_status, project_id, compile_status=exit_code, compile_duration=duration),
    by="project_id"
  )
  w_semanticdb <- left_join(
    w_compile,
    select(semanticdb_status, project_id, semanticdb_status=exit_code, semanticdb_duration=duration),
    by="project_id"
  )
  w_implicits <- left_join(
    w_semanticdb,
    select(implicits_status, project_id, implicit_status=exit_code, implicit_duration=duration),
    by="project_id"
  )
  w_implicits_stats <- left_join(
    w_implicits,
    select(implicits_stats, project_id, declarations, callsites, implicit_failure=failure, implicit_problems=failures),
    by="project_id"
  )
  w_implicits_stats
})
```

# Task summary

## Metadata

```{r}
metadata_status %>%
  show_task_exit_code_summary()
```
## Compile

```{r}
compile_status %>%
  show_task_exit_code_summary()
```

## Semanticdb

```{r}
semanticdb_status %>%
  show_task_exit_code_summary()
```

## Implicits

```{r}
implicits_status %>%
  show_task_exit_code_summary()
```

## Summary all projects

```{r}
projects_with_logs <- projects %>%
  select(
    project_id, 
    project_path, 
    origin, 
    metadata_status, 
    semanticdb_status, 
    implicit_status, 
    declarations, 
    callsites, 
    implicit_failure, 
    implicit_problems
    ) %>%
  mutate(
    metadata_log_file=projects_file(project_ids, METADATA_LOG),
    compile_log_file=projects_file(project_ids, COMPILE_LOG),
    semanticdb_log_file=projects_file(project_ids, SEMANTICDB_LOG),
    implicits_log_file=projects_file(project_ids, IMPLICITS_LOG)
  )

projects_with_logs %>% show_task_all_project_status()
```

## Implicits Exceptions

```{r}
exceptions <- read_csv(path(params$base_dir, IMPLICITS_EXCEPTIONS), col_types="ccccc")
```

```{r}
missing <- filter(exceptions, str_detect(message, "Unable to resolve")) %>% mutate(clazz=str_replace(message, "Unable to resolve: (.*)", "\\1")) %>% select(project_id, module_id, clazz)
count(missing, clazz)
missing_other <- filter(missing, !startsWith(clazz, "local"))
count(missing_other, clazz) %>% arrange(desc(n))
sum(implicits_stats$declarations)
sum(implicits_stats$callsites)
filter(missing, clazz=="scala/Predef.ArrowAssoc().") %>% count(project_id)
filter(missing, clazz=="scala/Predef.$conforms().") %>% count(project_id)
```

## Implicits stats

```{r}
implicits_stats %>% summarise_at(vars(declarations, callsites, failures), sum)
```

