---
title: "Task result"
output: html_document
editor_options: 
  chunk_output_type: console
params:
  taskname: "metadata"
  output_dir: "logs/latest"
---

```{r setup, include=FALSE}
library(tidyverse)
library(fs)
library(glue)
library(DT)
library(pbapply)

knitr::opts_chunk$set(echo = TRUE)

PROJECTS_DIRNAME <- "projects"
ANALYSIS_DIRNAME <- "_analysis_"
STATUS_FILENAME <- str_c(params$taskname, "-status.csv")
REPO_METADATA_FILENAME <- "repo-metadata.csv"
LOG_FILENAME <- str_c(params$taskname, ".log")

BASE_DIR <- "."
PROJECTS_DIR <- path(BASE_DIR, PROJECTS_DIRNAME)
OUTPUT_DIR <- params$output_dir
PROJECTS_FILE <- path(OUTPUT_DIR, "projects.txt")
OUTPUT_CWD_RELATIVE_DIR <- fs::path_rel(BASE_DIR, OUTPUT_DIR)
```

```{r load data, echo=FALSE, include=FALSE}
projects <- read_lines(PROJECTS_FILE)
projects_path <- path(PROJECTS_DIR, projects)

run_df <- data_frame(
  project_id=projects,
  origin=str_c("https://github.com/", str_replace(project_id, "--", "/")),
  taskname=params$taskname,
  path=path(OUTPUT_CWD_RELATIVE_DIR, projects_path)
)
```

```{r load results, echo=FALSE, include=FALSE}
results_files <- path(projects_path, ANALYSIS_DIRNAME, STATUS_FILENAME)
results_files_existing <- results_files[file_exists(results_files)]
results_df <- pbapply::pblapply(
  results_files_existing, 
  function(x) {
    ids <- basename(dirname(dirname(x)))
    status <- read_csv(x, col_types="cii", col_names=FALSE)
    if (length(status) != 3) {
      message(x, " length: ", length(status))
      NA
    } else {
      transmute(status, project_id=ids, exit_code=X2, duration=X3)
    }
  }
)

results_df <- results_df[!is.na(results_df)] %>% dplyr::bind_rows()

final_df <- 
  left_join(run_df, results_df, by="project_id") %>%
  mutate(log=path(path, ANALYSIS_DIRNAME, LOG_FILENAME)) %>%
  select(project_id, exit_code, everything())
```

## Summary for `r params$taskname`

```{r quick stats, echo=FALSE}
n_all_projects <- nrow(final_df)
n_successfull_projects <- nrow(filter(final_df, exit_code==0))
n_failed_projects <- n_all_projects - n_successfull_projects
```

There was `r n_all_projects` projects out of which succeeded `r n_successfull_projects` and failed `r n_failed_projects`.

Duration:
```{r delay summary}
summary(final_df$duration)
```

## Summary of exit code

```{r summary, echo=FALSE}
save_projects_by_exit_code <- function(code) {
  projects_ids <- dplyr::filter(final_df, exit_code==code)$project_id
  filename <- str_c("projects-exitcode-", code, ".txt")
  write_lines(projects_ids, path(OUTPUT_DIR, filename))
  filename
}

exit_codes <- count(final_df, exit_code) %>% replace_na(list(exit_code=-999))
exit_codes_paths <- mutate(exit_codes, path=sapply(exit_code, save_projects_by_exit_code))
exit_codes_paths %>% 
  mutate(path=glue("<a href='{path}' target='_blank'>{basename(path)}</a>")) %>%
  DT::datatable(escape=FALSE)
```

## Details

```{r table, echo=FALSE}
table <- 
  mutate(
    final_df, 
    project=glue("<a href='{origin}' target='_blank'>{project_id}</a>"), 
    path=glue("<a href='{path}' target='_blank'>{basename(path)}</a>"), 
    log=glue("<a href='{log}' target='_blank'>{basename(log)}</a>")
  ) %>%
  select(-origin)

display <- function(table) {
  DT::datatable(
    table,
    class='cell-border stripe',
    options=list(pageLength=100),
    escape=FALSE
  )
}

display(table)
```